logo:
  nav_mobile: images/reactql-logo.svg
  subbrand: images/logo-apollo-subbrands-developers-space.svg
  title: ReactQL Docs
  subtitle: Modern stack for React+GraphQL
  url: https://reactql.org

nav_links:
  'Main site':
    url: https://reactql.org
  'Github':
    url: https://github.com/leebenson/reactql
